site_name: Nim docs

theme:
  name: material
#  highlightjs: true

nav:
  - About: about.md
  - Manual:
    - Authors: manual/author.md

    - Lexis:
      - About: manual/lexis/about.md
      - Definitions: manual/lexis/definitions.md
      - Lexical Analysis: manual/lexis/lexical_analysis.md
      - Syntax: manual/lexis/syntax.md
      - Order of evaluation: manual/lexis/evaluation_order.md
      - Constants and Contants Expressions: manual/lexis/constants.md
      - Restrictions on Compile-Time Execution: manual/lexis/restrictions_compile_time_execution.md
    - Types: manual/types.md
    - Type Relations: manual/type_relations.md
    - Overload Resolution: manual/overload_resolution.md
    - Overload Disambiguation: manual/overload_disambiguation.md
    - Statements Expressions: manual/statements_expressions.md
    - Procedures: manual/procedures.md
    - Methods: manual/methods.md
    - Iterators and the for statement: manual/iterators_for.md
    - Converters: manual/converters.md
    - Type sections: manual/type_sections.md
    - Exception Handling: manual/exception_handling.md
    - Effect System: manual/effect_system.md
    - Generics: manual/generics.md
    - Templates: manual/templates.md
    - Macros: manual/macros.md
    - Special Types: manual/special_types.md
    - Modules: manual/modules.md
    - Compiler Messages: manual/compiler_messages.md
    - Pragmas:
      - Pragmas: manual/pragmas/pragmas.md
      - Implementation Specific Pragmas: manual/pragmas/specific_pragmas.md
      - User-defined pragmas: manual/pragmas/user_defined_pragmas.md
      - Foreign function interface: manual/pragmas/ffi.md
      
    - Threads: manual/threads.md



markdown_extensions:
- admonition
- codehilite
- pymdownx.details
- pymdownx.superfences

plugins:
- search